### ISSUE TITLE
OpenStreetMap baselayer: Correct attribution

### ISSUE THREAD

**Issue by jbelien** [osoc21/RoadBase#24]
Hello @osoc21/the-floof-fighters ,

Congratulations for using OpenStreetMap Belgium tileserver, we appreciate it !

**BUT** you completely miss the attribution !

- OpenStreetMap requires proper attribution : <https://www.openstreetmap.org/copyright>
- OpenStreetMap Belgium tileserver provider requires proper attribution : <https://github.com/jbelien/openstreetmap-carto-be/wiki/Tile-Usage-Policy>

**Comment by juliavdkris** [comment]
Hi Jonathan, thanks for pointing this out! We'll be sure to add proper attribution tomorrow :)

**Comment by jbelien** [comment]
Thanks but not quite there yet : 

> We require that you use the credit “© OpenStreetMap contributors”. 
> --- _Source: <https://www.openstreetmap.org/copyright>_

HTML code should be
```html
© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors. 
Tiles courtesy of <a href="https://geo6.be/">GEO-6</a>
```

**Comment by jbelien** [comment]
I also notice you used some crazy JavaScript to update the attribution.
That should not be necessary, all [`Layers`](https://leafletjs.com/reference-1.7.1.html#layer) in Leaflet have an [`attribution` property](https://leafletjs.com/reference-1.7.1.html#layer-attribution).
